name: app
description: Polkawallet built with Flutter.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.i.eventId == 'Reward';
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.3.2+3323

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.0.1
#  json_annotation: ^3.1.1
  get_storage: ^2.0.2
  biometric_storage: ^4.1.1
  # device_info: ^2.0.1
  package_info: ^2.0.2
  uni_links: ^0.5.1
  firebase_core: 1.5.0
  firebase_analytics: 8.3.0
  flutter_screenutil: ^5.0.0+2
#  firebase_messaging: 10.0.5
  update_app:
    git:
      url: https://github.com/mofada/flutter_update_app.git
      ref: c9e0f9ba9a7fe35aec0312847a4e481e4923cce1
  jpush_flutter:
    git:
      url: https://github.com/polkawallet-io/jpush-flutter-plugin.git
      ref: 23e6265cb2de247e3b8fc3a225b71d1e8c02fcf9
  polkawallet_plugin_kusama:
    git:
      url: https://github.com/polkawallet-io/polkawallet_plugin_kusama.git
      ref: 0d793bdbd95a76a3088b161d325de87a5db9da1d
  polkawallet_plugin_acala:
    git:
      url: https://github.com/AcalaNetwork/polkawallet_plugin_acala.git
      ref: 06994d689d8a92e7621b0f89bd0a181024ecb8a1
  polkawallet_plugin_karura:
    git:
      url: https://github.com/AcalaNetwork/polkawallet_plugin_karura.git
      ref: 03eb437bb059f5bc1e3988df5ac6bbca0e659bf9
  polkawallet_plugin_statemine:
    git:
      url: https://github.com/polkawallet-io/polkawallet_plugin_statemine.git
      ref: e2a9fc66914153a24b18a99c99b9895e96837c3f
  polkawallet_plugin_bifrost:
    git:
      url: https://github.com/bifrost-finance/polkawallet_plugin_bifrost.git
      ref: b5677954c17432ca6b32da4dd31929b0fa0c3171
  polkawallet_plugin_chainx:
    git:
      url: https://github.com/chainx-org/polkawallet_plugin_chainx.git
      ref: 2cc634bc4f0b873e7fe0801d5d3fba46756f5315
  polkawallet_plugin_edgeware:
    git:
      url: https://github.com/remzrn/polkawallet_plugin_edgeware.git
      ref: 11be316dc77b721d41ed6774fbf8d444a5a8eaa9
  polkawallet_plugin_dbc:
    git:
      url: https://github.com/DeepBrainChain/PolkaWallet_Plugin_DBC
      ref: 1cfd68ebbee73f2cf211dedf5eaf9332e8399a8d
  polkawallet_plugin_robonomics:
    git:
      url: https://github.com/Multi-Agent-io/polkawallet_plugin_robonomics.git
      ref: 480a3872cc684b72f3d1dad9e05871ea0dd82f04

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  # flutter_bugly: ^0.4.3
  # flutter_bugly_play:
  #   git:
  #     url: https://github.com/polkawallet-io/flutter_bugly.git
  #     ref: da653ff78e269d011d1224e368e70703794601a1
  flutter_mobx: ^2.0.0
  flutter_svg: ^1.0.3
  card_swiper: ^2.0.3
  simple_shadow: ^0.2.0
  sticky_headers: ^0.2.0

dependency_overrides:
  polkawallet_plugin_kusama:
    path: ../../coding/polkawallet/polkawallet_plugin_kusama
  polkawallet_plugin_acala:
    path: ../../coding/polkawallet/polkawallet_plugin_acala
  polkawallet_plugin_karura:
    path: ../../coding/polkawallet/polkawallet_plugin_karura
  polkawallet_plugin_statemine:
    path: ../../coding/polkawallet/polkawallet_plugin_statemine
#  polkawallet_ui: ^0.4.7
#  polkawallet_sdk: ^0.4.7
  polkawallet_ui:
     path: ../../coding/polkawallet/ui
  polkawallet_sdk:
     path: ../../coding/polkawallet/sdk
  transformer_page_view:
    git:
      url: https://github.com/polkawallet-io/transformer_page_view.git
      ref: 19f3b7c46d5e81653cf027baa2cbe8d629dc052d
  charts_flutter:
     git:
       url: https://github.com/google/charts
       path: charts_flutter
  flutter_svg: ^1.0.3
  webview_flutter: ^3.0.4
  cached_network_image: ^3.2.0
  flutter_html: ^2.2.1
  flutter_slidable: ^1.2.0
  platform: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  mobx_codegen: ^2.0.1+3
  json_serializable: ^4.1.2
#  build_runner: ^1.10.9
#  mobx_codegen: ^1.1.1
#  json_serializable: ^3.5.1
  flutter_launcher_icons: ^0.9.0
  rive: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/public/
    - assets/images/icons/
    - assets/images/plugins/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue.otf
          weight: 700
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-SemiBold.ttf
        - asset: assets/fonts/TitilliumWeb-Black.ttf
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
        - asset: assets/fonts/TitilliumWeb-BoldItalic.ttf
        - asset: assets/fonts/TitilliumWeb-ExtraLight.ttf
        - asset: assets/fonts/TitilliumWeb-ExtraLightItalic.ttf
        - asset: assets/fonts/TitilliumWeb-Italic.ttf
        - asset: assets/fonts/TitilliumWeb-Light.ttf
        - asset: assets/fonts/TitilliumWeb-LightItalic.ttf
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/TitilliumWeb-SemiBoldItalic.ttf
    - family: SF_Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Light.otf
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
